[package]
name = "rescan"
version = "0.1.0"
authors = ["Nathan Wiebe Neufeldt <wn.nathan@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
once_cell = "1"
rescan-macros = { path = "rescan-macros" }
